export const GET_POKEMONS = 'GET_POKEMONS_REQUEST'
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const GET_POKEMONS_ERROR = 'GET_POKEMONS_ERROR'

export const GET_GENERATIONS = 'GET_GENERATIONS_REQUEST'
export const GET_GENERATIONS_SUCCESS = 'GET_GENERATIONS_SUCCESS'
export const GET_GENERATIONS_ERROR = 'GET_GENERATIONS_ERROR'
